# This is a config for E2B sandbox template.
# You can use template ID (javfeftqqynderqxhrda) or template name (plato-onchain-next) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("plato-onchain-next") # Sync sandbox
# sandbox = await AsyncSandbox.create("plato-onchain-next") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('plato-onchain-next')

template_id = "javfeftqqynderqxhrda"
dockerfile = "e2b.Dockerfile"
template_name = "plato-onchain-next"
start_cmd = "/compile_page.sh"
cpu_count = 4
memory_mb = 4_096
team_id = "e451c4df-19b6-49e6-ac5c-3ff9a5cef5f2"
